//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIEWebPortal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationDetail
    {
        public int Id { get; set; }
        public int AppId { get; set; }
        public string AppCode { get; set; }
        public Nullable<int> AppOwnerId { get; set; }
        public Nullable<int> TesterId { get; set; }
        public Nullable<int> ServiceManagerId { get; set; }
        public Nullable<int> SolutionDeliveryManagerId { get; set; }
        public string ApplicationVersion { get; set; }
        public Nullable<int> DocModeId { get; set; }
        public Nullable<bool> NOEApplicationIsPrimary { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
