//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIEWebPortal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppOnboardDetail
    {
        public int AppOnboardId { get; set; }
        public int AppId { get; set; }
        public Nullable<int> BPUId { get; set; }
        public string Windows { get; set; }
        public string Web { get; set; }
        public string Office { get; set; }
        public string PrimaryTestContact { get; set; }
        public string ContactPersonForKT { get; set; }
        public Nullable<int> AppTypeId { get; set; }
        public string TechDependencies { get; set; }
        public Nullable<int> TestCount { get; set; }
        public string Criticality { get; set; }
        public string Url { get; set; }
        public string SubBPU { get; set; }
        public string NumberOfUsersId { get; set; }
        public string ProdURL { get; set; }
        public string NetworkType { get; set; }
        public string TestingType { get; set; }
        public string AccessToExternal { get; set; }
        public string UserType { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual BPU BPU { get; set; }
    }
}
