//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIEWebPortal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BPU()
        {
            this.Applications = new HashSet<Application>();
            this.AppOnboardDetails = new HashSet<AppOnboardDetail>();
            this.EMIETickets = new HashSet<EMIETicket>();
            this.UserRoleBPUMappings = new HashSet<UserRoleBPUMapping>();
            this.EMIETicketsArches = new HashSet<EMIETicketsArch>();
        }
    
        public int BPUId { get; set; }
        public string BPU1 { get; set; }
        public string BPUFullName { get; set; }
        public string OwningOrganization { get; set; }
        public Nullable<int> BPUTestLeadId { get; set; }
        public Nullable<int> RedmondLeadId { get; set; }
        public Nullable<int> EspooLeadId { get; set; }
        public string EngineeringTeamMembers { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppOnboardDetail> AppOnboardDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMIETicket> EMIETickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleBPUMapping> UserRoleBPUMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMIETicketsArch> EMIETicketsArches { get; set; }
    }
}
