//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIEWebPortal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoScheduler
    {
        public int siteid { get; set; }
        public string siteurl { get; set; }
        public string docmode { get; set; }
        public string testAdded { get; set; }
        public string testVerified { get; set; }
        public string prodAdded { get; set; }
        public Nullable<System.DateTime> datetimeToProdAdd { get; set; }
    }
}
