//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIEWebPortal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMIETicketsArch
    {
        public int TicketId { get; set; }
        public int AppId { get; set; }
        public Nullable<int> BPUId { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int ChangeTypeId { get; set; }
        public Nullable<int> ReasonForChangeId { get; set; }
        public string Comments { get; set; }
        public string BusinessImpact { get; set; }
        public Nullable<int> DocModeId { get; set; }
        public Nullable<bool> X_UAMetaTage { get; set; }
        public string X_UAMetaTageDetails { get; set; }
        public Nullable<bool> X_UAHonor { get; set; }
        public Nullable<bool> MultipleX_UA { get; set; }
        public Nullable<bool> ExternalFacingSite { get; set; }
        public string FQDN { get; set; }
        public string AppSiteLink { get; set; }
        public Nullable<int> FinalCRStatusId { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ProductionDeployDateStart { get; set; }
        public Nullable<System.DateTime> ProductionDeployDateEnd { get; set; }
        public string SandBoxFailureComments { get; set; }
        public string ProductionSuccessComments { get; set; }
        public string ProductionFailureComments { get; set; }
        public Nullable<bool> SandboxRollback { get; set; }
        public Nullable<bool> ProductionRollback { get; set; }
        public string SubDomainSiteLink { get; set; }
        public Nullable<int> SubDomainDocModeId { get; set; }
        public Nullable<bool> SubDomainX_UAHonor { get; set; }
        public Nullable<bool> DomainOpenInEdge { get; set; }
        public Nullable<bool> SubDomainOpenInEdge { get; set; }
        public string RejectedReason { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual BPU BPU { get; set; }
        public virtual DocMode DocMode { get; set; }
        public virtual EMIEChangeType EMIEChangeType { get; set; }
        public virtual EMIEReasonForChange EMIEReasonForChange { get; set; }
        public virtual EMIETicketStatu EMIETicketStatu { get; set; }
        public virtual User User { get; set; }
        public virtual DocMode DocMode2 { get; set; }
    }
}
