//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIEWebPortal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMIETicketAproval
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public Nullable<int> UserRoleBPUMappingId { get; set; }
        public string ApproverComments { get; set; }
        public Nullable<int> TicketStateId { get; set; }
        public Nullable<int> NoOfReminders { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual EMIETicket EMIETicket { get; set; }
        public virtual EMIETicketState EMIETicketState { get; set; }
        public virtual UserRoleBPUMapping UserRoleBPUMapping { get; set; }
    }
}
