//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIEWebPortal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int TestResultID { get; set; }
        public Nullable<int> AppId { get; set; }
        public Nullable<int> ResultTypeID { get; set; }
        public string BugIDS { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> TestPassID { get; set; }
        public string Windows { get; set; }
        public string Web { get; set; }
        public string Office { get; set; }
        public Nullable<int> IssueTypeID { get; set; }
        public string IEResult { get; set; }
        public string ChromeResult { get; set; }
        public Nullable<int> NoOfUsersID { get; set; }
        public Nullable<int> MS_EdgeResultID { get; set; }
        public Nullable<int> Win10ClassicIEResultID { get; set; }
        public Nullable<int> Win8_1IEResultID { get; set; }
        public Nullable<int> SubResultID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> BrowserID { get; set; }
        public string TesterName { get; set; }
        public Nullable<int> ApptypeID { get; set; }
        public Nullable<int> Desktop_StoreResultID { get; set; }
        public Nullable<int> Office16ResultID { get; set; }
        public Nullable<int> Desktop_StoreSubResultID { get; set; }
        public Nullable<int> Office16SubResultID { get; set; }
        public Nullable<System.DateTime> TestedDate { get; set; }
        public Nullable<int> CTID { get; set; }
    
        public virtual AppType AppType { get; set; }
        public virtual IssueType IssueType { get; set; }
        public virtual NoOfUser NoOfUser { get; set; }
        public virtual ResultType ResultType { get; set; }
        public virtual TestPass TestPass { get; set; }
    }
}
