//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIEWebPortal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_TelemetryData
    {
        public int Id { get; set; }
        public int AppId { get; set; }
        public int TechnologyId { get; set; }
        public string ActiveXGuid { get; set; }
        public int DomainId { get; set; }
        public string URL { get; set; }
        public int DocModeId { get; set; }
        public int DocModeReasonId { get; set; }
        public int BrowserStateReasonId { get; set; }
        public int CrashCount { get; set; }
        public int HangCount { get; set; }
        public string Extension { get; set; }
        public int SupportedAPIId { get; set; }
        public int DeprecatedAPIId { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual DocMode DocMode { get; set; }
        public virtual Technology Technology { get; set; }
        public virtual TM_APIDetails TM_APIDetails { get; set; }
        public virtual TM_APIDetails TM_APIDetails1 { get; set; }
        public virtual TM_BrowserStateReason TM_BrowserStateReason { get; set; }
        public virtual TM_DocModeReason TM_DocModeReason { get; set; }
        public virtual TM_Domain TM_Domain { get; set; }
    }
}
